def select_knowledge_pages(intent):
    knowledge_map = {
        "account_information": [
            "EBL Home Page",
            "EBL Retail Deposits Page",
            "EBL SME Deposits Page",
            "EBL Verified Contact Information",
        ],
        "card_information": [
            "EBL Cards Page",
            "EBL Verified Contact Information",
        ],
        "loan_information": [
            "EBL Retail Loan Page",
            "EBL SME Loan Page",
            "EBL Verified Contact Information",
        ],
        "deposit_information": [
            "EBL Retail Deposits Page",
            "EBL SME Deposits Page",
            "EBL Verified Contact Information",
        ],
        "digital_banking": [
            "EBL Digital Banking Page",
            "EBL Missed Call Alert Service Page",
            "EBL 365 PLUS Page",
            "EBL Verified Contact Information",
        ],
        "charge_information": [
            "EBL Schedule of Charges Page",
            "EBL Interest Rates Page",
            "EBL Foreign Exchange Rate Page",
            "EBL Verified Contact Information",
        ],
        "retail_banking": [
            "EBL Retail Loan Page",
            "EBL Retail Deposits Page",
            "EBL Cards Page",
            "EBL Digital Banking Page",
            "EBL Missed Call Alert Service Page",
            "EBL 365 PLUS Page",
            "EBL SKYPAY Page",
            "EBL Insta Account Branch Page",
            "EBL Insta Banking Online Page",
            "EBL Priority Banking Page",
            "EBL Power Banking Page",
            "EBL Super Saver Page",
            "EBL Women Banking Page",
            "EBL Agent Banking Page",
            "EBL Payroll Banking Page",
            "EBL Student Banking Page",
            "EBL Bancassurance Page",
            "EBL Retail Alliance Page",
            "EBL Verified Contact Information",
        ],
        "student_banking": [
            "EBL Student Banking Page",
            "EBL Junior Savings Account Page",
            "EBL Campus Account Page",
            "EBL Student File Services Page",
            "EBL Child Future Plan Page",
            "EBL Aspire Scheme Page",
            "EBL Little Star Page",
            "EBL Junior Saver's Islamic Account Page",
            "EBL Campus Islamic Account Page",
            "EBL Verified Contact Information",
        ],
        "islamic_banking": [
            "EBL Islamic Banking Page",
            "EBL Shariah Committee Page",
            "EBL Islamic Retail Finance Page",
            "EBL Islamic SME Finance Page",
            "EBL Islamic Corporate Finance Page",
            "EBL Islamic Cards Page",
            "EBL Islamic Profit Distribution Page",
            "EBL Verified Contact Information",
        ],
        "branch_locator": [
            "EBL Locator Page",
            "EBL Verified Contact Information",
        ],
    }

    return knowledge_map.get(intent, [
        "EBL Home Page",
        "EBL Verified Contact Information",
    ])
